### PR TITLE
Refactor: formatter code

### PR DESCRIPTION
**Pull request by kyklish**
Changes proposed in this pull request:

- remove redundant variables modification
- simplify oneCommandCode detection
- update test `180-if-else-braces` with `return` command
- add test for label fall-through scenario
- add test for label with specific names
- extract duplicate code to separate util function with tests

Notifying @mark-wiemer

### CODE REVIEW

**Comment by kyklish** [comment]
Waiting for all other PRs.

**Comment by kyklish** [comment]
Ready for review.

**Review by mark-wiemer — CHANGES_REQUESTED** [review]
Awesome, great work!

**Comment by kyklish** [comment]
Add `export type BraceChar = '{' | '}';`
Update tests with explicit type:
```AutoHotKey
        interface TestBraceData {
            in: string;
            bc: BraceChar;
            bn: number;
        }
        // List of test data
        let dataList: TestBraceData[] = [
        ...
```

**Review by mark-wiemer — APPROVED** [review]

**Pull request merged**
