### PR TITLE
Fix formatting after conditional expression with string literals

### LINKED ISSUE #18: Formatter indents on ternary operator
**Repro**
1. have sth like this code (this is from the [original docs](https://lexikos.github.io/v2/docs/Variables.htm#ternary) just with quotes around the 3)
```Autohotkey
var := x>y ? 2 : "3"
something("skdfjbv")
```
2. Perform **Format Document** with AHK++ >
```Autohotkey
var := x>y ? 2 : "3"
    something("skdfjbv")
```

The exact expression from the docs `var := x>y ? 2 : 3` does work properly tho!
It's just when there is a quoted string after the `:`

**Expected behavior**
The code should not change.

**Environment**

VS Code **1.53.0.0**
AutoHotkey Plus Plus **v2.5.12**

### PR DESCRIPTION
**Pull request by mark-wiemer**
Closes #18 .

Changes proposed in this pull request:
- Improve documentation and variable naming
- Fix #18

---

Replace "ISSUE" and "CHANGE" above with your values.

Do not edit below:

Notifying @mark-wiemer

### CODE REVIEW

**Comment by mark-wiemer** [comment]
Requesting review from @fade2grey and @fupeijiang

**Comment by FuPeiJiang** [comment]
wow, what a smart solution

I've tested it against 3500 lines of ahk_explorer.ahk and no breaking changes : and it fixed the indentation of ternary

I've tested it against my main script and no changes, I guess I don't have ternary ends

___
is there a way to automate formatting tests ?

**Comment by mark-wiemer** [comment]
Yes, there is absolutely a way to automate formatting tests. I plan on implementing Jest tests for as many things as possible in February, starting with the formatter. I'd appreciate any links to source code you're willing to share for these tests!

**Comment by FuPeiJiang** [comment]
it's not really a test, you can just hope it breaks something
https://github.com/FuPeiJiang/ahk_explorer/blob/tests/ahk_explorer.ahk

**Comment by FuPeiJiang** [comment]
I've heard about Mocha, but not Jest, what are the differences ?

**Comment by fade2gray** [comment]
> 
> 
> Requesting review from @fade2gray and @FuPeiJiang: Only substantial change is in `CodeUtil.ts`, I don't think it will affect `formattingProvider.ts`, asking for a second 👀
Limited test woks for a quoted string, but not if 3rd operand is left blank, i.e white space after the colon.

In order to test, I edited out\common\codeutils.js. I don't know if that was the correct method but it worked - but the code is different.

codeutils.js
```
    static purity(origin) {
        if (!origin)
            return '';
        // TODO: untest
        return origin
            .replace(/;.+/, '')
            //.replace(/".*?"/g, '')
            .replace(/".*?"/g, '""') // replace string literals with empty string literal

```

codeutils.ts
```
        if (!original) return '';
        return original
            .replace(/;.+/, '')
            .replace(/".*?"/g, '')
            .replace(/".*?"/g, '""') // replace string literals with empty string literal
            .replace(/\{.*?\}/g, '')
            .replace(/ +/g, ' ')
            .replace(/\bgui\b.*/gi, '')
```

**Comment by FuPeiJiang** [comment]
> Limited test woks for a quoted string, but not if 3rd operand is left blank, i.e white space after the colon.

ternary you must have 3rd operand : here: `"bar"`
`(expression) : "foo" ? "bar"`

___
to get the exact copy, you need to make a local branch from `upstream/fix-18`

`git checkout -b <local branch name> upstream/fix-18`

**Comment by mark-wiemer** [comment]
@fade2gray To test, you can simply pull this branch, open in VS Code, and press F5. That will recompile the code (updating the `out` folder and its contents) and launch a test window. I will prioritize contribution guidelines that make this easier once some dev QoL improvements have been made

**Comment by mark-wiemer** [comment]
@fade2gray You mentioned a failing case, but I'm not quite sure what you mean. Can you provide an example? The original code, the expected format, and the actual format provided?

**Comment by fade2gray** [comment]
> 
> ternary you must have 3rd operand : here: `"bar"`
> `(expression) : "foo" ? "bar"`

```
x := True
y := x = True ? 1 :
if y = 
    MsgBox False
Else
    MsgBox True
```

**Comment by FuPeiJiang** [comment]
this code is incorrect `y := x = True ? 1 :`
ternary always needs to return something, if it's empty string, you need to specify it
`y := x = True ? 1 : ""`

don't expect the formatter to work when you have code errors
you can expect a linter, a linter would be cool

**Comment by fade2gray** [comment]
> 
> 
> @fade2gray You mentioned a failing case, but I'm not quite sure what you mean. Can you provide an example? The original code, the expected format, and the actual format provided?

When using the ternary operator, if the operand after the colon is blank (whitespace), or a quoted string, undesired indentation occurs in the following lines. See [https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/issues/18#issuecomment-750332345](https://github.com/mark-wiemer/vscode-autohotkey-plus-plus/issues/18#issuecomment-750332345)

**Comment by mark-wiemer** [comment]
@fade2gray I was confused for a couple reasons
1. You stated that the syntax was `(expression) : "foo" ? "bar"` when it's really `(expression) ? "foo" : "bar"`
2. The code you provided has syntax errors. Formatters do not work on code with syntax errors, so this failure to format is outside the scope of this issue, and is something the compiler will catch.

**Comment by fade2gray** [comment]
> this code is incorrect `y := x = True ? 1 :`

It may be syntactically incorrect, but it functions and does not produce an error.

**Comment by FuPeiJiang** [comment]
true, it DOES work, wow

**Comment by FuPeiJiang** [comment]
if I works, I guess it's not incorrect

**Comment by fade2gray** [comment]
So is it an AHK bug?

**Comment by FuPeiJiang** [comment]
I would say a cool feature :)

**Comment by fade2gray** [comment]
Or is it something that can be referred to as a `side-effect`?

**Comment by fade2gray** [comment]
@mark-wiemer 
> I was confused because the code you provided has syntax errors. 

Even though it functions without error?

**Comment by mark-wiemer** [comment]
By definition, if it's syntactically incorrect, it doesn't function, it won't even compile. You were right, fade2gray, this is syntactically correct code. Who knew? I suppose we should update the formatter to support this, but that's a low priority since I doubt developers are using this much.

Note: `false ? 1 :` evaluates to empty string, and `true ? : 1` is also syntactically correct and evaluates to empty string. Same for `true ? :`. All of these expressions are whitespace-insensitive.

RE whether it's a bug: That's for the designer of the language to say. It's certainly not a behavior I expected, and it's not one I've ever seen before, but it may have been intended by Lexikos.

**Comment by mark-wiemer** [comment]
For now, I'm merging this PR to dev since it doesn't introduce any bugs and does fix the nominal use of the ternary operator with string literals. Thanks for the feedback everyone 🙂

**Comment by FuPeiJiang** [comment]
> false ? 1 : evaluates to empty string

how did you evaluate it ?

I did further testing and :
```autohotkey
print(false ? 1 :) ;print isn't even called
print(true ? : 1) ;print isn't even called
print(true ? :) ;print isn't even called
print(false ? :) ;print isn't even called
;so I guess it returns NOTHING instead of empty string
;it may be a bug, this is weird.

; print(true ? 645654 :) ;here print is called
print(string)
{
    msgbox, ok
    msgbox % string
}
```

**Comment by mark-wiemer** [comment]
@FuPeiJiang To evaluate, I simply assigned a variable to the result of the ternary expression, debugged the script with breakpoints, and inspected the value of the variable. You can also use `OutputDebug`

```autohotkey
y := true ? : 1
OutputDebug, % "<" y ">"
```

**Comment by FuPeiJiang** [comment]
`y := true ? : 1` is equivalent to `y:=`
but since variables default to empty string, there is no problem.

`func(true ? : 1)` : the function is not called for some reason
even if `func()` works perfectly fine

**Comment by mark-wiemer** [comment]
That makes me think this whole "leaving operands out of the conditional expression" stuff is a bug. In any case, it's outside the scope of this PR!

**Comment by fade2gray** [comment]
Just to close, [Lexikos says](https://www.autohotkey.com/boards/viewtopic.php?f=14&t=86304&sid=92e8474fd3dd11e56421a6ba6bfb7cbd) it was permitted in v1 for backward compatibility.

**Comment by fade2gray** [comment]
@mark-wiemer  Another formatting problem that could also be colon related > https://github.com/AutoHotkey-Plus/vscode-autohotkey/issues/67

**Pull request merged**
